__title__ = 'DataStructuresAndAlgorithms'
__description__ = 'Data structures and algorithms examples written in Python.'
__url__ = 'https://github.com/virtualmadden/Data.Structures.And.Algorithms'
__version_info__ = ('0', '0', '1')
__version__ = '.'.join(__version_info__)
__author__ = 'Jonathan Madden'
__maintainer__ = 'Jonathan Madden'
__license__ = 'MIT'
__copyright__ = '(c) 2018 by Jonathan Madden'
